### ISSUE TITLE
completion 的统计貌似有些问题

### ISSUE THREAD

**Issue by savokiss** [C-Dao/opencatd_worker#18]
发现在使用 `TransformStream` 统计 `completion.tokens` 时，总是为0。

```typescript
      async transform(chunk, controller) {
        const jsonString = `"${new TextDecoder().decode(chunk).slice(6)}"`;
        if (!jsonString.startsWith('"{') || !jsonString.endsWith('}"')) {
          controller.enqueue(chunk);
          return;
        }
        const json = JSON.parse(jsonString);
        allContent += json.choices.map((it: any) => it.dekta.content).join("");
        controller.enqueue(chunk);
      },
```

上面代码的 JSON.parse 貌似一直不走。
发现回来的 chunk 都是一半一半的，我使用的 CF worker，不知道是不是我本地环境的问题？

**Comment by benmix** [comment]
使用最新的 https://github.com/C-Dao/opencatd_worker/pull/17 的代码部署还是有问题吗？

**Comment by benmix** [comment]
有复现的方式吗，能简单描述一下吗？感谢！

**Comment by savokiss** [comment]
用的是最新的代码，我是直接在 `transform` 中直接打印 `new TextDecoder().decode(chunk)` 这个就可以看到 trunk 不是完整的，有时候有一半。
所以经常走不到下面计算 `allContent` 的地方，导致后面的 `completion tokens` 的值一直都是0。

---

查到了 vercel 上有关于这个问题的说明，可能是网络环境影响的：

https://vercel.com/docs/concepts/functions/edge-functions/streaming#caveats

使用 `eventsource-parser` 应该可以解决，不知道加入到在此仓库会不会导致包太大~

**Comment by benmix** [comment]
这个我周末才有时间修复，如果你有解决办法的话，也欢迎提交 PR，感谢反馈！

**Comment by savokiss** [comment]
嗯嗯，我先研究研究，有解决的话我提交一个~
